name: Push to GCS Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: cs-tmpl-test
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Push file to GCS Bucket
        run: |
          gsutil cp /c/Users/NAVYA/Desktop/code.txt gs://<bucket_name>/destination file path
 
