name: second-job
on: push
jobs:
   job1:
      name: first-job
      runs-on: ubuntu-latest
      steps:
      - name: step one
        uses: action/checkout@v2
      - name: step two
        run: date  
    job2:
      name: first-job
      runs-on: windows-latest
      steps:
      - name: step one
        uses: action/checkout@v2
      - name: step two
        run: date   
   
