name: second-job
on: push
jobs:
    jobs1:
       name: first-job
       runs-on: ubuntu-latest
       steps:
       - name: step one
         uses: action/checkout@v2
       - name: step two
         run: date  
     
